In [15]:
import numpy as np

# BP 神经网络
# python 3.7

In [19]:
# 输入数据
X= np.array([[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
# 标签
Y=np.array([[0,1,1,0]])
# 权值初始化，1行3列，取值范围 -1到1
V=np.random.random((3,4))*2-1
W=np.random.random((4,1))*2-1
print(X)
print(Y)
print(V)
print(W)
# 学习率设置
lr=0.11

def sigmoid(x):
    return 1/(1+np.exp(-x))  # sigmoid 函数取值 0~1之间
def dsigmoid(x):
    return x*(1-x)
def update():
    global X,Y,W,V,lr
    l1=sigmoid(np.dot(X,V)) # 隐藏层输出(4,4)
    l2=sigmoid(np.dot(l1,W)) #输出层输出(4,1)
    
    l2_delta=(Y.T-l2)*dsigmoid(l2)
    l1_delta=l2_delta.dot(W.T)*dsigmoid(l1)
    
    wc=lr*l1.T.dot(l2_delta)
    vc=lr*X.T.dot(l1_delta)
    W=W+wc
    V=V+vc
    

[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[[0 1 1 0]]
[[ 0.6293333   0.86936642 -0.03467937  0.92710823]
 [-0.37902046 -0.18830448 -0.68106243  0.28558169]
 [-0.46358425 -0.62022989 -0.85098258 -0.2992744 ]]
[[0.58570645]
 [0.60455402]
 [0.63325711]
 [0.09203143]]


In [28]:
for i in range(2000):
    update()  # 更新权值
    if(i%500)==0:
        l1=sigmoid(np.dot(X,V)) # 隐藏层输出 (4,4)
        l2=sigmoid(np.dot(l1,W)) # 输出层输出 (4,1)
        print('loss:',np.mean(np.abs(Y.T-l2)))
l1=sigmoid(np.dot(X,V)) # 隐藏层输出 (4,4)
l2=sigmoid(np.dot(l1,W)) # 输出层输出 (4,1)
print(l2)
def judge(x):
    if x>=0.05:
        return 1
    else:
        return 0;
for i in map(judge,l2):
    print(i)

loss: 0.010617487426624671
loss: 0.0105836420941354
loss: 0.010550107978642293
loss: 0.01051688039088508
[[0.010614  ]
 [0.99311911]
 [0.98698519]
 [0.01142638]]
0
1
1
0
